version: '3.5'


services:
        angular-service:
                container_name: frontend1
                build: ./
                volumes:
                        - './:/usr/src/app'
                ports:
                        - "4200:80"
                command: "npm start"
